# Generated by Django 5.2.7 on 2025-11-19 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_initial'),
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Resource',
            new_name='Room_Resources',
        ),
        migrations.DeleteModel(
            name='TimeSlot',
        ),
    ]
