# Generated by Django 5.2.7 on 2025-11-19 11:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_initial'),
        ('rooms', '0002_delete_timeslot'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['resource', 'starts_at', 'ends_at'], name='bookings_bo_resourc_16b817_idx'),
        ),
    ]
